version: 2.1
orbs:
  node: circleci/node@1.1.6
  # use Cypress orb for e2e
  cypress: cypress-io/cypress@1
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
workflows:
  lint:
    jobs:
      - lint
  test:
    jobs:
      - test
  e2e:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:4200'
  build:
    jobs:
      - build
